name: Unit test execution

on:
  push:


jobs:
  test:
    runs-on: [ubuntu-latest]
    name: Unittests
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3.13'
      - name: Install Composer Dependencies
        run: composer install
      - name: Unit tests run
        shell: bash
        run: |
          vendor/bin/phpunit
