name: Unit test execution

on:
  push:


jobs:
  test:
    runs-on: [ubuntu-latest]
    name: Unittests
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3.13'
      - name: Install Composer Dependencies
        run: composer install
      - name: Unit tests run
        shell: bash
        run: |
          vendor/bin/phpunit --log-junit junit.xml --coverage-clover coverage.xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
